# 服务器配置
server:
   port: 8081

# 日志配置
logging:
   pattern:
      console: '%d{yyyy-MM-dd} [%thread] %-5level %logger{50} - %msg%n'
      file: '%d{yyyy-MM-dd} === [%thread] === %-5level === %logger{50} ==== %msg%n'
   level: {root: INFO, com.sdxh.weixin.dao: INFO}
   file:
      name: 'd:/print.log'